### ISSUE TITLE
openai_base

### ISSUE THREAD

**Issue by zxqSled** [weiyifan1023/Neeko#3]
Hi, I think this is a very great job and I would like to try to follow it.,but, due to my weak engineering skills, I don't know how to set  api-key and api_base in the eval. Could you please help me, Thank you very much!!
looking forword to your reply~~

**Comment by weiyifan1023** [comment]
Please enter the third party transfer URL (ending in /v1, please skip here if you use the official OpenAI API)
e.g. (https://api.openai.com/v1)

The **api key** is configured in the get_api_key function of the eval_utils.py

**Comment by zxqSled** [comment]
> Please enter the third party transfer URL (ending in /v1, please skip here if you use the official OpenAI API) e.g. (https://api.openai.com/v1)
> 
> The **api key** is configured in the get_api_key function of the eval_utils.py

ok~thanks!!

**Comment by weiyifan1023** [comment]
If there is no problem, we will close this issue
